version: '3'
services:
  varenya_server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: varenya_server
    env_file:
      - server.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - varenya_net
    depends_on:
      - varenya_postgres

  varenya_postgres:
    image: postgres
    container_name: varenya_postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - postgres.env
    volumes:
      - varenya_postgres:/var/lib/postgresql/data
    networks:
      - varenya_net

networks:
  varenya_net:
    name: varenya_net

volumes:
  varenya_postgres:
    driver: local
