version: '3'
services:
  varenya_server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: varenya_server
    env_file:
      - server.env
      - firebase-admin.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - varenya_net
    depends_on:
      - varenya_postgres

  varenya_postgres:
    image: postgres
    container_name: varenya_postgres
    restart: always
    ports:
      - '127.0.0.1:8888:5432'
      - '5432:5432'
    env_file:
      - postgres.env
    volumes:
      - varenya_postgres:/var/lib/postgresql/data
    networks:
      - varenya_net
      - pg_net

  varenya_pgadmin:
    container_name: varenya_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '127.0.0.1:9000:80'
    networks:
      - pg_net

networks:
  varenya_net:
    name: varenya_net
  pg_net:
    name: pg_net

volumes:
  varenya_postgres:
    driver: local
